# Generated by Django 2.2.28 on 2024-02-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
